### ISSUE TITLE
Move all Grafana dashboards to IaC

### ISSUE THREAD

**Issue by sitilge** [Rpc-h/applications#12]
Currently all our Grafana dashboards are created manually and stored in ephemeral storage. Move all dashboards to IaC using the following template:

```yaml
apiVersion: v1
data:
  dashboard.json: |
    {

    }
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    grafana_dashboard: "1"
  name: abc123
  namespace: monitoring
```
